### ISSUE TITLE
Choosing a colour palette from the client's website / brand materials.

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/marketing#5]

**Comment by cararthompson** [comment]
Here's a proposed outline:

*Hook*
You've collected the data, performed all the analyses, figured out the best way to plot the main story... Next step: tie the look of the plot in with the topic so that readers react with "ooh, nice story about [x]" rather than "look, they used ggpplot!".

*Overall concept*
In our consultancy work, we want the plots we create to blend in seamlessly with the bigger picture of what our clients want to communicate, A big part of that is choosing a colour palette that aligns with the colours used by the client. 

Several other aspects to this, (covered elsewhere?)
- fonts (do you have a post on using custom fonts that you could use here?)
- use of labels (more or less word / shadow text post)
- visual simplicity/complexity (do you have a post on using theme_minimal()?)
- colours (the focus of this post!)

*How to*
1. Choose colours
- They have one main colour in their branding? Try a monochrome palette around that colour
- They have give you brand guidlines? Use those if you can (are there enough colours for your plots?)
- You need to come up with colours from their other materials? I use https://imagecolorpicker.com/ a lot for this; plug in an image or a website, and either go with the suggested palette, or pick out specific colours (more often)

2. Use custom colour scales (the code bit)
- Worked example creating a scale and using it in a plot (points / background)

3. Extra steps: accessibilty
- Check for how it will look to people with different types of visual impairments, tweak as needed
- Point to packages that help with that

*Summary*
In following these steps, the plot becomes part of the bigger picture, rather than being a stand alone item - it helps the client tell the story rather than detracting from it.

**Comment by cararthompson** [comment]
In terms of examples, we could go with CBEM, but the thing there is that they gave us the palette... and didn't use the plot where I followed the steps I'm outlining here to create an on-brand colour theme where more colours were required. 

If you're open to using a non rfortherest plot, I think the most on-brand one I've done is this one about the weather in Edinburgh (it ties in with the Festival colour scheme / font  / local colloquialisms...). 

![image](https://user-images.githubusercontent.com/14091282/148564693-1e74236a-38c3-46a6-85fb-b5099a74b810.png)

**Comment by cararthompson** [comment]
Which makes me think, do you want tips on using colours in text, or shall we save that for another post? My go-to for that is to use ggtext and the element_markdown() options in the theme settings.

**Comment by dgkeyes** [comment]
This looks great, Cara. 

My major piece of feedback is to keep the focus on colors and avoid everything else (fonts, labels, etc). Those are each big topics on their own and I don't want the main focus to be lost. 

Let's really have the blog post focus as: You're working with an organization and here are their colors. How do you translate that into code that you can use in R to make graphs that reflect their color scheme? The meat of the post is about creating custom color scales so everything else should build up to that. 

In terms of an example, I'm fine to have you use the one above. You can use that as an example and I'll also add links to several R for the Rest of Us projects where we've used organizations' brand colors. That will help, hopefully, to generate some additional consulting work.

**Comment by cararthompson** [comment]
The structure of this is taking shape and I have notes on the process I followed to determine the colibri colours, so I can use the code for that in the examples. Here's the proposed structure:

- Hook (why this is a good idea, see above)
- Step 1: Get hold of the colours (client provided these ones, but otherwise colorpicker is a useful website)
- Step 2: Play around with them using dummy data (very quick note on why I like palmerpenguins), see how they balance with each other (in our case, the green was too bright and needed to be toned down to work in dataviz)
- Step 3: Create color/fill scales (with easy to follow code example)
- Step 4: Put it all through colorblindr to see what it looks like and tweak accordingly
- Step 5: Determine colours for the NAs and for Text as an extra nice touch

Tada, branded plot and color/fill scales you can apply to any plot within the project.

**Comment by dgkeyes** [comment]
Sounds great! Onward ho!

**Comment by cararthompson** [comment]
I'm going you try to get this done today and tomorrow so I can take Friday off. Keep me right, do you want this in the first person ("here's how I approach things") or on behalf of the team ("here's what we did")?

**Comment by dgkeyes** [comment]
Go ahead and do first person. I may edit later on but let's start with that.

**Comment by cararthompson** [comment]
I've just pushed a draft. I feel it's too long, but I'm going to wait for your feedback before tweaking it, so you can let me know where there's too much /  not enough detail.

**Comment by cararthompson** [comment]
Just quick note to say I tweaked the code a bit in the scale_fill/color bit to make it easier to read than what we have in the real code in the package, which has extra functionalities we don't need for this post.

**Comment by dgkeyes** [comment]
Ok, I've finished taking a pass editing this. Take a look [here](https://rfortherestofus.com/?p=24498) (you'll need to be logged in to access that) and let me know what you think.

**Comment by cararthompson** [comment]
Thanks for the edits - my PhD supervisors used to tell me my sentences were too long and this definitely feels more easy to read than the original.

Two things if I may:
- We flip-flop between 1st person being me and me being "one of our team members" when you introduce monochromeR
- The first image for Step 3 isn't the right one. Let me know if you need me to provide it

Other than that, I'm happy for you to go ahead and publish it.

**Comment by cararthompson** [comment]
Oh and this is super vain of me, but any chance we could realign my profile pic with the one I'm using on Twitter? I can send you the file if you want or feel free to grab it from my profile.

**Comment by dgkeyes** [comment]
Very happy to do so! Could you send it to me on Twist or by email?

**Comment by dgkeyes** [comment]
Can you also point me to the right image for Step 3? Not sure what happened there.

**Comment by dgkeyes** [comment]
Oh, and I updated the "one of our team members" sentence. I was going to do it third person starting out but then switched, but forgot to update that.

**Comment by cararthompson** [comment]
> Can you also point me to the right image for Step 3? Not sure what happened there.

It should be generated by the code but I've exported it and emailed it to you just in case.
